language: python
python:
  - "3.6"
# install
install:
  - pip install pandas
  - pip install matplotlib
  - pip install statistics
  - pip install pycodestyle
# command to run tests
script:
  - pycodestyle BillCalculator.py
  - python BillCalculator.py < commands.txt